SELECT  A.ANIMAL_ID
        ,A.ANIMAL_TYPE
        ,A.NAME
  FROM  ANIMAL_INS AS A
  LEFT
  JOIN  ANIMAL_OUTS AS B
    ON  A.ANIMAL_ID = B.ANIMAL_ID
 WHERE  A.SEX_UPON_INTAKE IN ('INTACT MALE','INTACT FEMALE') AND B.SEX_UPON_OUTCOME IN ('NEUTERED MALE', 'SPAYED FEMALE')
 ORDER
    BY  A.ANIMAL_ID